name: E2E Tests with Docker

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  e2e-docker-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lightweight tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app:ro \
            -w /app \
            ghcr.io/${{ github.repository_owner | downcase }}/msearch-e2e:latest \
            test:lightweight

      - name: Run unit tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app:ro \
            -w /app \
            ghcr.io/${{ github.repository_owner | downcase }}/msearch-e2e:latest \
            test:unit

      - name: Run E2E tests in Docker (if not CI)
        if: github.event_name != 'push' || github.ref != 'refs/heads/develop'
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app:ro \
            -w /app \
            ghcr.io/${{ github.repository_owner | downcase }}/msearch-e2e:latest \
            test:e2e