name: Test Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'Dockerfile.e2e'
      - 'docker-entrypoint.sh'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.e2e
          push: false
          tags: msearch-e2e:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Test run container
        run: |
          docker build -f Dockerfile.e2e -t msearch-e2e:test .
          docker run --rm msearch-e2e:test test:unit || echo "Test container ready"